blank_issues_enabled: true
contact_links:
  - name: Security report
    url: https://github.com/sorrowfeng/libAutoUpdater/security/advisories/new
    about: Please report security vulnerabilities privately.
