#pragma once

#include "libAutoUpdater/Result.h"
#include "libAutoUpdater/interfaces/IStateStore.h"

#include <cstdint>
#include <string>
#include <vector>

namespace autoupdater::detail {

/// Opaque release and wall-clock context used to bound advisory download-resume
/// metadata. releaseKey is a credential-free lowercase SHA-256 generated by
/// the download coordinator. maxAgeSeconds is an inclusive retention window;
/// records older than the window are ignored and removed by the next apply.
struct DownloadResumeScope {
    std::string releaseKey;
    std::uint64_t nowUnixSeconds = 0;
    std::uint64_t maxAgeSeconds = 0;
};

/// Internal optional capability used by the bundled JSON store. Keeping this
/// outside the public IStateStore contract preserves existing custom-store
/// vtables; stores without the capability continue through the single-record
/// fallback in DownloadExecutor.
class IDownloadResumeBatchStore {
  public:
    virtual ~IDownloadResumeBatchStore() = default;

    /// Loads only requested records that belong to scope.releaseKey and are no
    /// older than scope.maxAgeSeconds. This operation never mutates storage.
    virtual Result<std::vector<DownloadResumeState>>
    loadDownloadResumeBatch(const DownloadResumeScope& scope, const std::vector<std::string>& keys) noexcept = 0;

    /// Reloads under the store's cross-process lock, prunes stale/other-release
    /// records, applies clears followed by upserts, and atomically publishes at
    /// most one resume-state snapshot. A no-op must not rewrite the snapshot.
    virtual Result<void> applyDownloadResumeBatch(const DownloadResumeScope& scope,
                                                  const std::vector<DownloadResumeState>& upserts,
                                                  const std::vector<std::string>& clears) noexcept = 0;
};

} // namespace autoupdater::detail
